install.packages("ape")
install.packages("phangorn")
require(ape)
require(phangorn)
x<-read.dna("mustelid_coI.fasta",format="fasta")
d<-dist.dna(x)
write.table(as.matrix(d),"distances.csv")
d
d2<-dist.dna(x, model="GTR")
tr.upgma<-upgma(d)
plot(tr.upgma)
tr.upgmar<-root(tr.upgma, outgroup="Melursus/1-601 urinus")
plot(tr.upgmar);nodelabels();add.scale.bar(length=0.001)
plot(tr.upgma,"f")
tr.nj<-nj(d)
plot(tr.nj)
plot(tr.nj,"p")
plot(tr.nj,"f")
plot(tr.nj,"p")
par(mfrow=c(1,2))
plot(tr.upgma,"f")
plot(tr.nj,"p")
par(mfrow=c(1,1))
dt.upgma<-cophentic(tr.upgma)
dt.upgma<-cophenetic(tr.upgma)
dmat<-as.matrix(d)
nms<-rownames(dmat)
dt.upgma<-dt.upgma[nms, nms]
d
dt.upgma<-as.dist(dt.upgma)
plot(dt.upgma-d,ylab="residuals", cex=0.5,main="UPGMA")
abline(h=0,lty=3)
tr.fast<-fastme.bal(d,nni=T,spr=T,tbr=T)
plot(tr.fast)
par(mfrow=c(2,2))
plot(tr.nj)
plot(tr.bionj)
plot.phylo(tr.bionj)
fit<-pml(tr.upgma,as.phyDat(x))
fit=optim.pml(fit,T)
plot(fit)
par(mfrow=c(1,1))
plot(fit)
set.seed(8)
bs<-bootstrap.pml(fit,bs=100,optNni=T)
treeBS<-plotBS(fit$tree, type="fan", bs)
treeBS<-plotBS(fit$tree, type="p", bs)
mt<-modelTest(as.phyDat(x),G=F,I=F)
dhky<-dist.dna(x,model="GTR")
orig<-evol.distinct(tr.upgma,type="fair.proportion")
orig
orig<-evol.distinct(tr.upgma,type="fair.proportion")orig
plot(tr.fast)
par(mfrow=c(2,2))
par(mar=rep(1,4))
plot(tr.upgma,"f")
plot(dt.upgma-d,ylab="residuals", cex=0.5,main="UPGMA")
plot(tr.fast)
plot.phylo(tr.bionj)
plot(tr.bionj)
plot(tr.nj)
plot(fit)
treeBS<-plotBS(fit$tree, type="fan", bs)
treeBS<-plotBS(fit$tree, type="p", bs)
View(mt)
View(dmat)
par(mfrow=c(1,1))
par(mar=rep(1,1))
plot(dt.upgma-d,ylab="residuals", cex=0.5,main="UPGMA")
